# Generated by Django 4.2.1 on 2023-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
            ],
            options={
                'verbose_name': 'Контест',
                'verbose_name_plural': 'Контесты',
            },
        ),
    ]
