# Generated by Django 4.2.1 on 2023-06-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
