# Generated by Django 4.2.1 on 2023-06-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0003_alter_problem_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Решений'),
        ),
    ]
