# Generated by Django 4.2.1 on 2023-06-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Посылка', 'verbose_name_plural': 'Посылки'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='testset_dir',
            field=models.FilePathField(path='static/tests/', verbose_name='Тестовые данные'),
        ),
    ]
