# Generated by Django 4.2.1 on 2023-06-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submission_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='memory',
            new_name='memory_consumed',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='testset_dir',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time',
        ),
        migrations.AddField(
            model_name='submission',
            name='time_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='Время'),
        ),
    ]
