# Generated by Django 4.2.1 on 2023-06-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_rename_memory_submission_memory_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='relative_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время прошедшее с начала контеста'),
        ),
    ]
