# Generated by Django 4.2.1 on 2023-06-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_relative_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory_consumed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='passed_tests_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество пройденных тестов'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('in queue', 'In queue'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong answer', 'Wrong answer'), ('time limit exceeded', 'Time limit exceeded'), ('runtime error', 'Runtime error'), ('compilation error', 'Compilation error'), ('ignored', 'Ignored')], max_length=19, null=True, verbose_name='Вердикт'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_consumed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Время'),
        ),
    ]
