# Generated by Django 4.2.1 on 2023-06-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_memory_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('in queue', 'In queue'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong answer', 'Wrong answer'), ('time limit exceeded', 'Time limit exceeded'), ('runtime error', 'Runtime error'), ('compilation error', 'Compilation error'), ('ignored', 'Ignored')], default=('in queue', 'In queue'), max_length=19, null=True, verbose_name='Вердикт'),
        ),
    ]
