# Generated by Django 4.2.1 on 2023-06-03 19:40

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Почта')),
                ('nickname', models.CharField(max_length=70, unique=True, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.generate_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Аватар')),
                ('first_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, max_length=512, null=True, verbose_name='Обо мне')),
                ('problems_solved', models.PositiveIntegerField(default=0, verbose_name='Решено задач')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('github', models.CharField(blank=True, max_length=32, null=True)),
                ('show_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
